name: ECS Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  Something:
    runs-on: ubuntu-latest
    steps:
      - run: echo "We did thing!"
