name: ECS Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  build-image:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Docker image is creating.."

  push-image:
    name: "Push Docker Image"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Docker image is pushing to ECR.."
  task-definition:
    name: "Creating task definition"
    runs-on: ubuntu-latest
    steps:
      - run: echo "ECS task definition is updating..."
  deploy-service:
    name: "Service deploy"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Service is deploying..."
