name: ECS Deploy Simulation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  build-and-push-docker-image:
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          echo "Building Docker image for ${{ github.event.inputs.environment }} environment..."
          # docker build -t my-image:${{ github.sha }} .
          echo "Docker image built successfully."

      - name: Push Docker Image
        run: |
          echo "Pushing Docker image to registry... to ${{ github.ref_name }}"
          # docker push my-image:${{ github.sha }}
          echo "Docker image pushed successfully."

  update-ecs-task-definition:
    name: Update ECS Task Definition
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update ECS Task Definition
        run: |
          echo "Updating ECS task definition for ${{ github.event.inputs.environment }} environment..."
          # Simulate updating ECS task definition
          echo "ECS task definition updated successfully."

  deploy-ecs-service:
    name: Deploy ECS service to ${{ github.event.inputs.environment }}
    needs: update-ecs-task-definition
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy ECS Service
        run: |
          echo "Deploying ECS service for ${{ github.event.inputs.environment }} environment..."
          # Simulate ECS service deployment
          echo "ECS service deployed successfully."
